DATABASE:
  host: localhost
  user: root
  password: 
  database: the_wall
  port: 3306

PORT: 8080

SESSION_SECRET: 
# creating 24 hours from milliseconds
# (1000 * 60) * 60 * 24
SESSION_EXPIRE: 86400000